### ISSUE TITLE
Should filter_leeloolxp be a depedency?

### ISSUE THREAD

**Issue by mudrd8mz** [anayleeloolxp/moodle-block_tb_courses#1]
So if the filter_leeloolxp is needed to actually display the content, should it be declared as a dependency?

And then, then is the point of having this as an extra plugin then?

**Comment by anayleeloolxp** [comment]
Well this block_tb_courses plugins works on its on. It doesnt need filter_leeloolxp as dependency. You can normally use block_tb_courses as a block.

But to add the block on any content by shortcode, we did the filter plugin.

I hope i am clear.

**Comment by mudrd8mz** [comment]
Ah, I see. I had troubles to get the actual content displayed. OK then, makes sense. Thanks.
