### ISSUE TITLE
Invalid JSON response from leelooxp.com

### ISSUE THREAD

**Issue by mudrd8mz** [anayleeloolxp/moodle-block_tb_courses#2]
Like other leelooxp plugins also this one seems to suffer of https://github.com/anayleeloolxp/moodle-block_tb_latestentry/issues/2

However, even after I learned how to force my Moodle to re-load the setting from the LeelooXP.com, I am getting response that is not a valid JSON and as such the block method `get_content()` sees `$resposedata` as empty and does not do anything.

This is the response I get:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>404 Page Not Found</title>
<style type="text/css">

::selection { background-color: #E13300; color: white; }
::-moz-selection { background-color: #E13300; color: white; }

body {
	background-color: #fff;
	margin: 40px;
	font: 13px/20px normal Helvetica, Arial, sans-serif;
	color: #4F5155;
}

a {
	color: #003399;
	background-color: transparent;
	font-weight: normal;
}

h1 {
	color: #444;
	background-color: transparent;
	border-bottom: 1px solid #D0D0D0;
	font-size: 19px;
	font-weight: normal;
	margin: 0 0 14px 0;
	padding: 14px 15px 10px 15px;
}

code {
	font-family: Consolas, Monaco, Courier New, Courier, monospace;
	font-size: 12px;
	background-color: #f9f9f9;
	border: 1px solid #D0D0D0;
	color: #002166;
	display: block;
	margin: 14px 0 14px 0;
	padding: 12px 10px 12px 10px;
}

#container {
	margin: 10px;
	border: 1px solid #D0D0D0;
	box-shadow: 0 0 8px #D0D0D0;
}

p {
	margin: 12px 15px 12px 15px;
}
</style>
</head>
<body>
	<div id="container">
		<h1>404 Page Not Found</h1>
		<p>The page you requested was not found.</p>	</div>
</body>
</html>
```

**Comment by anayleeloolxp** [comment]
@mudrd8mz  The issue for invalid json is fixed. Also have commented here https://github.com/anayleeloolxp/moodle-block_tb_latestentry/issues/2 Please check that.

**Comment by mudrd8mz** [comment]
Thanks. Was the fix server-side only? Was a new plugin version needed?

**Comment by anayleeloolxp** [comment]
It was a server side fix, the Leeloo code was not updated on the install we have shared with you. So have updated it, and that have solved the issue.
